/**
 * Semantic Document Architecture Types
 * 
 * This file defines the TypeScript interfaces for the new semantic document model
 * that anchors comments to content blocks instead of fragile positions.
 */

/**
 * Represents a semantic document with stable block-based structure
 */
export interface SemanticDocument {
  id: string;
  title: string;
  blocks: DocumentBlock[];
  metadata: DocumentMetadata;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * A semantic block within the document
 */
export interface DocumentBlock {
  id: string; // Stable UUID that never changes
  type: BlockType;
  content: string; // Plain text content
  position: number; // Display order only
  children?: DocumentBlock[]; // For nested structures
  annotations: Annotation[];
  metadata?: BlockMetadata;
  isImmutable?: boolean; // If true, block content cannot be changed except by user
  createdAt?: Date; // When the block was first created
  lastUserEdit?: Date; // When user last manually edited this block
}

/**
 * Types of document blocks
 */
export type BlockType = 
  | 'paragraph' 
  | 'heading' 
  | 'list' 
  | 'quote' 
  | 'code' 
  | 'divider';

/**
 * An annotation (comment, suggestion, etc.) attached to a document block
 */
export interface Annotation {
  id: string;
  type: AnnotationType;
  author: 'ai' | 'user';
  content: string;
  targetBlockId: string; // Stable reference to the block
  targetText?: string; // Optional: specific text within the block
  createdAt: Date;
  updatedAt: Date;
  resolved: boolean;
  resolvedAt?: Date;
  resolvedBy?: string;
  metadata?: AnnotationMetadata;
}

/**
 * Types of annotations
 */
export type AnnotationType = 
  | 'comment' 
  | 'suggestion' 
  | 'critique' 
  | 'praise' 
  | 'question' 
  | 'highlight';

/**
 * Document-level metadata
 */
export interface DocumentMetadata {
  essayId?: string;
  prompt?: string;
  wordLimit?: number;
  author?: string;
  version?: number;
  tags?: string[];
}

/**
 * Block-level metadata
 */
export interface BlockMetadata {
  wordCount?: number;
  characterCount?: number;
  readingTime?: number;
  complexity?: 'low' | 'medium' | 'high';
}

/**
 * Comment categories for the sidebar organization
 */
export type CommentCategory = 
  | 'overall-analysis'
  | 'tone'
  | 'clarity'
  | 'strengths'
  | 'areas-for-improvement'
  | 'paragraph-quality'
  | 'grammar';

/**
 * Annotation-level metadata
 */
export interface AnnotationMetadata {
  confidence?: number; // For AI-generated annotations
  agentType?: 'big-picture' | 'paragraph' | 'weaknesses' | 'strengths' | 'tone' | 'clarity' | 'grammar';
  category?: 'overall' | 'inline';
  subcategory?: 'opening' | 'body' | 'conclusion' | 'opening-sentence' | 'transition' | 'paragraph-specific' | 'paragraph-quality' | 'final-sentence' | 'grammar';
  commentNature?: 'strength' | 'weakness' | 'suggestion' | 'improvement';
  commentCategory?: CommentCategory; // New field for sidebar categorization
}

/**
 * AI comment generation request
 */
export interface AICommentRequest {
  documentId: string;
  blocks: DocumentBlock[];
  context: EssayContext;
  options?: AICommentOptions;
}

/**
 * AI comment generation response
 */
export interface AICommentResponse {
  success: boolean;
  comments: SemanticComment[];
  message?: string;
  metadata?: {
    processingTime: number;
    blocksAnalyzed: number;
    commentsGenerated: number;
  };
}

/**
 * A comment generated by AI using semantic blocks
 */
export interface SemanticComment {
  targetBlockId: string; // Always stable
  targetText?: string; // Precise text selection within block
  comment: string;
  type: AnnotationType;
  confidence: number;
  metadata?: AnnotationMetadata;
}

/**
 * Context for essay analysis
 */
export interface EssayContext {
  prompt?: string;
  wordLimit?: number;
  schoolType?: 'undergraduate' | 'graduate' | 'mba';
  applicationDeadline?: Date;
  targetSchools?: string[];
}

/**
 * Options for AI comment generation
 */
export interface AICommentOptions {
  focusAreas?: ('opening' | 'body' | 'conclusion' | 'transitions' | 'overall')[];
  commentTypes?: AnnotationType[];
  maxComments?: number;
  minConfidence?: number;
}

/**
 * Document operations for the semantic editor
 */
export interface DocumentOperations {
  addBlock: (block: Omit<DocumentBlock, 'id' | 'annotations'>) => DocumentBlock;
  updateBlock: (blockId: string, updates: Partial<DocumentBlock>) => DocumentBlock | null;
  deleteBlock: (blockId: string) => boolean;
  moveBlock: (blockId: string, newPosition: number) => boolean;
  addAnnotation: (annotation: Omit<Annotation, 'id' | 'createdAt' | 'updatedAt'>) => Annotation;
  updateAnnotation: (annotationId: string, updates: Partial<Annotation>) => Annotation | null;
  deleteAnnotation: (annotationId: string) => boolean;
  resolveAnnotation: (annotationId: string, resolvedBy: string) => boolean;
}

/**
 * Editor state for the semantic editor
 */
export interface SemanticEditorState {
  document: SemanticDocument;
  selectedBlockId?: string;
  selectedAnnotationId?: string;
  isEditing: boolean;
  isCommenting: boolean;
  pendingChanges: boolean;
}

/**
 * Event types for the semantic editor
 */
export type SemanticEditorEvent = 
  | { type: 'block-selected'; blockId: string }
  | { type: 'annotation-selected'; annotationId: string }
  | { type: 'annotation-added'; annotation: Annotation }
  | { type: 'annotation-updated'; annotation: Annotation }
  | { type: 'annotation-deleted'; annotationId: string }
  | { type: 'document-changed'; document: SemanticDocument }
  | { type: 'ai-comments-generated'; comments: Annotation[] };

/**
 * Migration utilities for converting from old system
 */
export interface LegacyComment {
  id: string;
  text_selection: {
    start: { pos: number; path: number[] };
    end: { pos: number; path: number[] };
  };
  anchor_text: string;
  comment_text: string;
  comment_type: string;
  paragraph_id?: string;
  paragraph_index?: number;
  ai_generated: boolean;
  resolved: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * Migration result
 */
export interface MigrationResult {
  success: boolean;
  document: SemanticDocument;
  migratedComments: number;
  failedComments: number;
  errors: string[];
}
