-- Create essay comments table for inline commenting functionality
CREATE TABLE public.essay_comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  essay_id UUID NOT NULL REFERENCES essays(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id),
  
  -- Comment positioning in the essay
  text_selection JSONB NOT NULL, -- {start: {pos: 0, path: [0,0]}, end: {pos: 5, path: [0,0]}}
  anchor_text TEXT, -- The actual text being commented on
  
  -- Comment content
  comment_text TEXT NOT NULL,
  comment_type VARCHAR(20) DEFAULT 'suggestion' CHECK (comment_type IN ('suggestion', 'critique', 'praise', 'question')),
  
  -- AI metadata
  ai_generated BOOLEAN DEFAULT false,
  ai_model VARCHAR(50), -- gpt-4, claude, etc.
  confidence_score DECIMAL(3,2) CHECK (confidence_score >= 0 AND confidence_score <= 1),
  
  -- Status
  resolved BOOLEAN DEFAULT false,
  resolved_at TIMESTAMP WITH TIME ZONE,
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create comment threads for replies
CREATE TABLE public.comment_threads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_comment_id UUID NOT NULL REFERENCES essay_comments(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id),
  reply_text TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes for performance
CREATE INDEX idx_essay_comments_essay_id ON essay_comments(essay_id);
CREATE INDEX idx_essay_comments_user_id ON essay_comments(user_id);
CREATE INDEX idx_essay_comments_ai_generated ON essay_comments(ai_generated);
CREATE INDEX idx_essay_comments_resolved ON essay_comments(resolved);
CREATE INDEX idx_essay_comments_created_at ON essay_comments(created_at);

CREATE INDEX idx_comment_threads_parent_id ON comment_threads(parent_comment_id);
CREATE INDEX idx_comment_threads_user_id ON comment_threads(user_id);

-- Enable RLS
ALTER TABLE public.essay_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comment_threads ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for essay_comments
CREATE POLICY "Users can view comments on their essays" 
ON public.essay_comments 
FOR SELECT 
USING (
  auth.uid() = user_id OR 
  essay_id IN (
    SELECT id FROM essays WHERE user_id = auth.uid()
  )
);

CREATE POLICY "Users can create comments on their essays" 
ON public.essay_comments 
FOR INSERT 
WITH CHECK (
  essay_id IN (
    SELECT id FROM essays WHERE user_id = auth.uid()
  )
);

CREATE POLICY "Users can update their own comments" 
ON public.essay_comments 
FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own comments" 
ON public.essay_comments 
FOR DELETE 
USING (auth.uid() = user_id);

-- Create RLS policies for comment_threads
CREATE POLICY "Users can view threads for their essay comments" 
ON public.comment_threads 
FOR SELECT 
USING (
  auth.uid() = user_id OR 
  parent_comment_id IN (
    SELECT id FROM essay_comments 
    WHERE essay_id IN (
      SELECT id FROM essays WHERE user_id = auth.uid()
    )
  )
);

CREATE POLICY "Users can create threads on their essay comments" 
ON public.comment_threads 
FOR INSERT 
WITH CHECK (
  parent_comment_id IN (
    SELECT id FROM essay_comments 
    WHERE essay_id IN (
      SELECT id FROM essays WHERE user_id = auth.uid()
    )
  )
);

CREATE POLICY "Users can update their own thread replies" 
ON public.comment_threads 
FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own thread replies" 
ON public.comment_threads 
FOR DELETE 
USING (auth.uid() = user_id);

-- Create triggers for automatic timestamp updates
CREATE TRIGGER update_essay_comments_updated_at
BEFORE UPDATE ON public.essay_comments
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_comment_threads_updated_at
BEFORE UPDATE ON public.comment_threads
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Add helpful comments
COMMENT ON TABLE essay_comments IS 'Stores inline comments and AI feedback for essays';
COMMENT ON TABLE comment_threads IS 'Stores replies to essay comments';
COMMENT ON COLUMN essay_comments.text_selection IS 'TipTap editor position data for anchoring comments to specific text';
COMMENT ON COLUMN essay_comments.anchor_text IS 'The actual text snippet being commented on';
COMMENT ON COLUMN essay_comments.ai_generated IS 'Whether this comment was generated by AI';
COMMENT ON COLUMN essay_comments.confidence_score IS 'AI confidence score (0.00 to 1.00)';
