// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otlbklcvzbcbrnamgtsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90bGJrbGN2emJjYnJuYW1ndHNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjAwOTEsImV4cCI6MjA2OTc5NjA5MX0.UFqtHseTnep26jJIYW8_gjawq5ffPzG4PaePTU5FO7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});